services:
  emp-frontend:
    # image: khanster/frontend:latest
    container_name: emp-frontend
    build:
      context: .
    ports:
      - "80:8080"
    networks:
      - angular
    volumes:
      - .:/usr/app
      - ./.m2:/root/.m2

networks:
  angular:
    name: angular
    external: true
